### ISSUE TITLE
Commerce Base dependency

### ISSUE THREAD

**Issue by jonty17** [drupalcommerce/commerce_base#13]
I am trying to update admin_toolbar to version 3.x and getting composer dependency issues

<code>Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for drupalcommerce/commerce_base dev-8.x-1.x -> satisfiable by drupalcommerce/commerce_base[dev-8.x-1.x].
    - Can only install one of: drupal/admin_toolbar[3.0.0, 2.x-dev].
    - Can only install one of: drupal/admin_toolbar[3.x-dev, 2.x-dev].
    - Can only install one of: drupal/admin_toolbar[3.0.1, 2.x-dev].
    - Can only install one of: drupal/admin_toolbar[3.0.2, 2.x-dev].
    - Conclusion: install drupal/admin_toolbar 2.x-dev
    - Installation request for drupal/admin_toolbar ^3.0 -> satisfiable by drupal/admin_toolbar[3.0.0, 3.x-dev, 3.0.1, 3.0.2].</code>

I found commerce base - which has this code - and specifies 2.x for admin toolbar. I guess I need to push this through the Commerce issue queue.

<code>{
  "name": "drupalcommerce/commerce_base",
  "type": "drupal-profile",
  "description": "Commerce 2.x installation profile",
  "homepage": "https://github.com/drupalcommerce/commerce_base",
  "license": "GPL-2.0+",
  "require": {
      "drupal/commerce": "^2.0",
      "drupal/admin_toolbar": "^2.0",
      "drupal/swiftmailer": "^2.0"
    }
}</code>

**Comment by jsacksick** [comment]
Fixed today.

**Comment by jonty17** [comment]
you've got it down as ^3.2 - current release is 3.0.2 - this needs to be ^3.0
